# Generated by Django 3.0.5 on 2020-04-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwword',
            new_name='password',
        ),
    ]
